services:
  bot:
    image: ghcr.io/lbr88/mmchatgpt:latest
    restart: unless-stopped
    #build: .
    environment:
      REDIS_HOST: redis
      REDIS_DB: 0
    links:
      - redis
    labels:
      com.centurylinklabs.watchtower.scope: mmchatgpt
    command: [ 'python', 'bot.py' ]
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app-data:/app-data
  redis:
    image: redis:7.2.5-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command:
      [
        'redis-server',
        '--save',
        '60',
        '1',
        '--loglevel',
        'warning'
      ]
    expose:
      - "6379"
  watchtower:
    image: containrrr/watchtower:1.7.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope mmchatgpt
    restart: unless-stopped
volumes:
  redis-data:
  app-data:
