version: '3'

volumes:
  redis-data:

services:
  bot:
    build: .
    environment:
      REDIS_HOST: redis
    links:
      - redis
    command: ['python', 'bot.py']
    env_file:
      - .env
  redis:
    image: redis
    volumes:
      - redis-data:/data
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning']
    expose:
      - "6379"