services:
  watchtower:
    image: busybox
    entrypoint: /bin/true
    volumes: []
    restart: "no"
    command: []
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - pg
    depends_on:
      - pg
volumes:
  pgadmin-data: