services:
  bot:
    image: ghcr.io/aio-it/mmchatgpt:latest
    restart: unless-stopped
    #build: .
    environment:
      VALKEY_HOST: valkey
      VALKEY_DB: 0
    links:
      - valkey
    labels:
      com.centurylinklabs.watchtower.scope: mmchatgpt
    command: [ 'python', 'bot.py' ]
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app-data:/app-data
  valkey:
    image: valkey/valkey:8.0.1-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    expose:
      - "6379"
  #watchtower:
  #  image: containrrr/watchtower:1.7.1
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --interval 30 --scope mmchatgpt
  #  restart: unless-stopped
volumes:
  redis-data:
  app-data:
