apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-env
data:
  MM_URL: "https://mm.nyvej.it"
  MM_API_PATH: "/api/v4"
  MM_PORT: "443"
  MM_SSL_VERIFY: "true"
  MM_BOT_TEAM: "nyvej"
  MM_BOT_ADMINS: "lbr"
  REDIS_DB: "0"
  REDIS_HOST: "redis"
  OLLAMA_URL: "http://nyvej.it:11434/api"
