apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "replace-me"
  MM_BOT_TOKEN: "replace-me"
  MM_BOT_LOG_CHANNEL: "replace-me"
  GIPHY_API_KEY: "replace-me"
  HIBP_API_KEY: "replace-me"
  ANTHROPIC_API_KEY: "replace-me"
