apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower
  labels:
    app: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower
  template:
    metadata:
      labels:
        app: watchtower
    spec:
      containers:
        - name: watchtower
          image: containrrr/watchtower:1.7.1
          command:
            - --interval
            - "30"
            - --scope
            - mmchatgpt
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
